In [48]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [49]:
df = pd.read_csv('messy_retail_dataset.csv')

In [50]:
df.head()

,OrderID,OrderDate,CustomerID,Country,Region,Product,Quantity,UnitPrice,Discount,ShippingMode,Category,Sales,Profit
0,10063,2022-10-23,1072,Canada,West,Printer,2,556,0.03,Express,Office,1112,372.051169
1,10498,2024-11-01,1063,Mexico,Central,Tablet,2,1851,0.33,EXPRESS,Electronics,3702,122.411691
2,10314,2024-05-16,1005,Japan,Central,Headphones,5,491,0.06,Same Day,Accessories,2455,413.755788
3,10109,2024-03-05,1025,Germany,North,Laptop,6,120,0.12,Same Day,Electronics,720,109.349998
4,10762,2022-11-14,1177,Germany,North,Printer,4,1504,0.22,Standard,Office,6016,873.037023

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1040 entries, 0 to 1039
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       1040 non-null   int64
 1   OrderDate     1040 non-null   object
 2   CustomerID    1040 non-null   int64
 3   Country       1015 non-null   object
 4   Region        1013 non-null   object
 5   Product       1040 non-null   object
 6   Quantity      1040 non-null   int64
 7   UnitPrice     1040 non-null   int64
 8   Discount      1015 non-null   float64
 9   ShippingMode  1040 non-null   object
 10  Category      1040 non-null   object
 11  Sales         1040 non-null   int64
 12  Profit        1014 non-null   float64
dtypes: float64(2), int64(5), object(6)
memory usage: 105.8+ KB

In [52]:
df.columns

Index(['OrderID', 'OrderDate', 'CustomerID', 'Country', 'Region', 'Product',
       'Quantity', 'UnitPrice', 'Discount', 'ShippingMode', 'Category',
       'Sales', 'Profit'],
      dtype='object')

In [53]:
df[['Country','Region']].isnull().sum()

Country    25
Region     27
dtype: int64

In [54]:
df.isnull().sum()

OrderID          0
OrderDate        0
CustomerID       0
Country         25
Region          27
Product          0
Quantity         0
UnitPrice        0
Discount        25
ShippingMode     0
Category         0
Sales            0
Profit          26
dtype: int64

In [55]:
df[df.isnull().any(axis=1)]

,OrderID,OrderDate,CustomerID,Country,Region,Product,Quantity,UnitPrice,Discount,ShippingMode,Category,Sales,Profit
6,10513,2022-02-10,1135,Brazil,South,Mobile,8,159,NaN,Standard,Electronics,1272,79.547088
12,10687,2023-06-21,1088,NaN,East,Smartwatch,6,592,0.20,EXPRESS,Electronics,3552,871.843934
20,10915,2024-11-08,1026,NaN,North,Mobile,6,1469,0.23,standard,Electronics,8814,-971.677824
31,10083,2022-10-16,1043,NaN,Central,Smartwatch,2,1361,0.16,Express,Electronics,2722,576.342393
35,10723,2022-01-04,1164,Brazil,East,Headphones,7,1213,0.23,EXPRESS,Accessories,8491,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
979,10252,2022-06-30,1122,Brazil,Central,Smartwatch,3,1226,0.33,Same Day,Electronics,3678,NaN
1017,10448,2024-10-29,1014,Japan,Central,Laptop,7,1837,NaN,Express,Electronics,12859,-581.399917
1023,10509,2023-11-29,1044,Germany,West,Mobile,3,1294,0.20,Express,Electronics,3882,NaN
1029,10993,2022-01-29,1048,NaN,North,Keyboard,7,548,0.19,Same Day,Accessories,3836,611.747148
1039,10546,2023-01-20,1121,Australia,West,Keyboard,7,1301,0.39,Same Day,Accessories,9107,NaN

In [56]:
#to check the percentage 
df[['Country','Region']].isnull().mean()*100

Country    2.403846
Region     2.596154
dtype: float64

In [57]:
# to check there is one region by country or multiple region
df.groupby("Country")["Region"].unique()

Country
Australia    [South, North, Central, East, West, nan]
Brazil       [South, Central, West, East, North, nan]
Canada       [West, North, South, Central, East, nan]
France            [East, Central, North, South, West]
Germany      [North, East, West, South, Central, nan]
India        [South, Central, East, West, North, nan]
Japan        [Central, North, South, West, East, nan]
Mexico       [Central, North, West, East, South, nan]
UK           [South, West, North, East, Central, nan]
USA          [East, North, West, Central, South, nan]
Name: Region, dtype: object

In [58]:
# Now check which region appears most frequently for each country.
df.groupby(['Country','Region']).size().sort_values(ascending=False)

Country    Region
France     West       32
Brazil     East       26
Japan      North      26
           East       26
Germany    East       25
Japan      Central    25
France     Central    24
UK         South      24
Germany    West       24
Canada     East       24
USA        North      24
Canada     Central    23
Brazil     North      23
Australia  North      23
           South      23
India      West       23
Mexico     North      22
France     East       22
India      East       22
Germany    Central    22
Brazil     Central    21
Australia  West       21
Germany    North      21
Japan      South      21
Australia  Central    20
Canada     South      20
India      North      20
France     North      19
USA        West       19
UK         West       18
Australia  East       18
USA        Central    17
Brazil     West       17
           South      16
Canada     West       16
           North      16
India      South      16
France     South      16
Mexico     South      16
USA        South      16
Mexico     West       16
UK         Central    16
           East       16
Mexico     Central    15
USA        East       15
Germany    South      14
UK         North      14
Japan      West       13
Mexico     East       13
India      Central    10
dtype: int64

In [59]:
df.shape

(1040, 13)

In [60]:
#👉 Are the same rows missing both Country and Region?
df[(df['Country'].isnull() ) | (df['Region'].isnull())]

,OrderID,OrderDate,CustomerID,Country,Region,Product,Quantity,UnitPrice,Discount,ShippingMode,Category,Sales,Profit
12,10687,2023-06-21,1088,NaN,East,Smartwatch,6,592,0.20,EXPRESS,Electronics,3552,871.843934
20,10915,2024-11-08,1026,NaN,North,Mobile,6,1469,0.23,standard,Electronics,8814,-971.677824
31,10083,2022-10-16,1043,NaN,Central,Smartwatch,2,1361,0.16,Express,Electronics,2722,576.342393
48,10824,2022-05-10,1072,NaN,South,Keyboard,6,565,0.28,standard,Accessories,3390,NaN
75,10953,2024-04-02,1171,NaN,North,Tablet,7,348,0.14,Express,Electronics,2436,600.915863
143,10717,2022-08-17,1056,USA,NaN,Headphones,2,387,0.08,EXPRESS,Accessories,774,227.059886
158,10958,2022-05-31,1122,Australia,NaN,Laptop,4,594,0.19,Standard,Electronics,2376,514.537976
169,10583,2024-02-06,1040,Brazil,NaN,laptop,6,1186,0.25,standard,Office,7116,1075.352632
182,10958,2022-05-31,1122,Australia,NaN,Laptop,4,594,0.19,Standard,Electronics,2376,514.537976
238,10316,2024-07-24,1079,India,NaN,Mobile,4,566,0.20,Express,Electronics,2264,-191.459758
251,10122,2023-06-25,1116,Mexico,NaN,Tablet,5,1419,0.23,standard,Electronics,7095,517.136540
287,10632,2024-10-25,1003,Germany,NaN,Camera,4,1737,0.35,Same Day,Electronics,6948,166.149643
345,10529,2024-04-03,1167,Japan,NaN,Tablet,6,1302,0.21,Standard,Electronics,7812,-848.955907
347,10249,2022-10-07,1019,NaN,Central,Monitor,8,1742,0.08,standard,Electronics,13936,4759.231620
375,10210,2022-12-04,1036,Brazil,NaN,Mobile,7,87,0.02,Express,Electronics,609,249.741956
376,10753,2022-09-18,1180,UK,NaN,Laptop,7,1653,0.40,EXPRESS,Electronics,11571,-3195.433632
397,10341,2022-06-03,1169,NaN,Central,Smartwatch,7,957,0.39,Express,Electronics,6699,676.415224
416,10730,2022-07-13,1155,Germany,NaN,Smartwatch,2,938,0.14,Standard,Electronics,1876,509.410833
429,10641,2024-12-05,1095,NaN,South,Tablet,5,634,0.33,standard,Electronics,3170,407.795220
448,10885,2023-10-26,1042,NaN,North,Keyboard,7,1114,0.22,Standard,Accessories,7798,1134.413340
454,10306,2024-12-12,1185,Canada,NaN,Headphones,3,424,0.23,EXPRESS,Accessories,1272,336.944951
456,10728,2024-08-04,1043,India,NaN,Monitor,8,1489,0.08,standard,Electronics,11912,786.541037
473,10008,2024-05-21,1086,NaN,Central,Headphones,7,1044,0.32,Express,Accessories,7308,-150.373716
477,10235,2024-08-17,1073,NaN,West,Mouse,4,1621,0.24,EXPRESS,Accessories,6484,-50.863755
491,10886,2022-01-25,1175,UK,NaN,Smartwatch,8,1997,0.25,standard,Electronics,15976,2495.553403
509,10417,2023-02-01,1014,USA,NaN,Headphones,7,1337,0.33,Same Day,Accessories,9359,-362.613689
512,10712,2024-01-29,1132,Mexico,NaN,Mouse,2,1556,0.15,Express,Accessories,3112,-15.955399
518,10823,2024-04-23,1012,NaN,West,Smartwatch,2,1550,0.37,Same Day,Electronics,3100,258.162906
523,10805,2022-06-06,1146,Australia,NaN,Smartwatch,1,422,0.21,Express,Electronics,422,-33.207462
533,10010,2024-02-09,1105,Brazil,NaN,Smartwatch,1,289,0.09,EXPRESS,Electronics,289,71.144757
590,10472,2023-04-21,1092,NaN,South,Mouse,2,1846,0.04,standard,Accessories,3692,1310.374520
632,10646,2022-08-02,1065,NaN,East,Monitor,2,609,0.05,Express,Electronics,1218,89.870227
635,10793,2023-05-18,1144,NaN,East,Headphones,2,1992,0.15,Same Day,Accessories,3984,440.939438
661,10491,2024-06-04,1187,NaN,West,Mobile,4,213,0.21,EXPRESS,Electronics,852,-18.020722
675,10957,2024-02-14,1046,Brazil,NaN,Mobile,2,277,0.16,Standard,Electronics,554,-3.845788
704,10838,2022-12-29,1082,Japan,NaN,Laptop,2,1487,0.16,Express,Electronics,2974,963.919547
739,10253,2023-08-30,1162,Mexico,NaN,Monitor,7,1311,0.30,Standard,Electronics,9177,113.143247
751,10093,2024-11-22,1061,NaN,East,Keyboard,7,187,0.13,EXPRESS,Accessories,1309,62.365384
780,10394,2023-09-09,1191,NaN,South,Keyboard,2,698,0.35,Express,Accessories,1396,-289.865181
806,10268,2022-06-04,1097,UK,NaN,Mobile,1,297,0.01,Standard,Electronics,297,NaN
825,10360,2024-03-12,1016,NaN,West,Monitor,4,326,0.33,EXPRESS,Electronics,1304,159.467896
829,10704,2024-05-26,1013,NaN,Central,Headphones,7,1071,0.12,standard,Accessories,7497,1218.725590
840,10631,2024-12-10,1036,NaN,Central,Mobile,9,775,0.07,EXPRESS,Electronics,6975,247.333715
845,10695,2022-04-21,1163,NaN,Central,Smartwatch,4,245,0.32,EXPRESS,Electronics,980,100.462916
870,10464,2022-06-16,1052,India,NaN,Printer,1,1256,0.32,Same Day,Office,1256,204.051341
898,10563,2023-03-25,1113,NaN,West,Headphones,9,1440,0.40,standard,Accessories,12960,842.013465
948,10805,2022-06-06,1146,Australia,NaN,Smartwatch,1,422,0.21,Express,Electronics,422,-33.207462
956,10273,2024-01-29,1122,USA,NaN,Laptop,6,1289,0.14,standard,Electronics,7734,1733.465904
963,10892,2023-10-24,1170,NaN,NaN,Mobile,4,1867,0.06,EXPRESS,Electronics,7468,-2778.817414
966,10799,2023-01-26,1071,Australia,NaN,Headphones,7,184,0.06,standard,Accessories,1288,60.457478
1029,10993,2022-01-29,1048,NaN,North,Keyboard,7,548,0.19,Same Day,Accessories,3836,611.747148

In [61]:
df.duplicated().sum()

np.int64(40)

In [62]:
#Drop the duplicate
df.drop_duplicates(inplace=True)

In [63]:
df.sort_values(by="OrderID",inplace=True,ignore_index=True)

In [64]:
df.head()

,OrderID,OrderDate,CustomerID,Country,Region,Product,Quantity,UnitPrice,Discount,ShippingMode,Category,Sales,Profit
0,10001,2024-05-10,1165,Germany,South,Headphones,9,1357,0.14,Standard,Accessories,12213,2548.376394
1,10002,2024-12-31,1033,UK,North,Tablet,4,51,0.17,Same Day,Electronics,204,6.142379
2,10003,2024-11-10,1016,Mexico,North,Smartwatch,7,306,0.31,Standard,Electronics,2142,324.025711
3,10004,2022-05-02,1164,Japan,West,Keyboard,6,613,0.19,EXPRESS,Accessories,3678,439.805380
4,10005,2023-04-12,1152,Japan,East,Laptop,2,1086,0.32,EXPRESS,Electronics,2172,-470.616919

In [65]:
df.Country.unique()

array(['Germany', 'UK', 'Mexico', 'Japan', 'India', nan, 'Brazil',
       'Canada', 'USA', 'Australia', 'France'], dtype=object)

In [66]:
## my conclusion to fill region nan where country is present 
#sypoose brazil have null havlue in region i will fill with is most brazil region are came like 
# Country    Region 
# France     West       30
# Brazil     East       26
# Japan      East       26
# Germany    East       24
# UK         South      24
# Japan      North      23
# Canada     East       23
# India      West       23
# Japan      Central    23
# Brazil     North      23
# Germany    West       23
# Canada     Central    22
# USA        North      22
# Mexico     North      22
# India      East       22
# Brazil     Central    21
# France     Central    21

df.Region[df["Country"]=="Brazil"].fillna("North")

9        North
27        East
40        West
41     Central
65       North
        ...
939      North
951      South
956      North
970       West
995      South
Name: Region, Length: 106, dtype: object

In [67]:
df.loc[df["Country"] == "Germany", "Region"]

0        South
11       North
19        East
30        West
46        West
        ...
971      North
977       West
984    Central
987       East
998       West
Name: Region, Length: 103, dtype: object

In [68]:
df.loc[df["Country"] == 'Brazil', "Region"]

9          NaN
27        East
40        West
41     Central
65       North
        ...
939      North
951      South
956        NaN
970       West
995      South
Name: Region, Length: 106, dtype: object

In [69]:
for i in df["Country"].dropna().unique():
    a = df[df["Country"] == i]["Region"]
    df.loc[df["Country"] == i, "Region"] = df.loc[df["Country"] == i, "Region"].fillna(a.mode()[0])

In [70]:
df["Region"].isnull().sum()

np.int64(1)

In [71]:
for i in df.Country.dropna().unique():
    print(i)
    a=df[df["Country"]==i]["Region"]
    # df["Region"].fillna(a.mode(),inplace=True)
    df.Region[df["Country"]==i].fillna(a.mode()[0],inplace=True)

Germany
UK
Mexico
Japan
India
Brazil
Canada
USA
Australia
France

In [72]:
df[df['Country']=='Brazil']['Region'].isnull().sum()

np.int64(0)

In [73]:
df.Region.isnull().sum()

np.int64(1)

In [74]:
# Option 2 (Business datasets often do this)

# Fill with "Unknown"

df["Country"] = df["Country"].fillna("Unknown")

In [75]:
df.isnull().sum()

OrderID          0
OrderDate        0
CustomerID       0
Country          0
Region           1
Product          0
Quantity         0
UnitPrice        0
Discount        25
ShippingMode     0
Category         0
Sales            0
Profit          24
dtype: int64

In [76]:
df[(df['Profit'].isnull() ) | (df['Discount'].isnull())]

,OrderID,OrderDate,CustomerID,Country,Region,Product,Quantity,UnitPrice,Discount,ShippingMode,Category,Sales,Profit
11,10012,2024-03-16,1026,Germany,North,Camera,8,1779,0.10,standard,Electronics,14232,NaN
17,10018,2022-09-10,1011,UK,South,Keyboard,6,245,NaN,EXPRESS,Accessories,1470,41.118103
33,10034,2024-04-20,1180,USA,South,Keyboard,6,572,NaN,EXPRESS,Accessories,3432,983.501888
79,10080,2023-08-16,1011,Brazil,East,Smartwatch,2,1173,NaN,Same Day,Electronics,2346,NaN
111,10112,2024-11-04,1009,Mexico,Central,Monitor,2,1572,0.18,Standard,Electronics,3144,NaN
164,10165,2022-05-24,1157,France,North,Laptop,9,1351,NaN,Same Day,Electronics,12159,5351.025121
201,10202,2023-08-10,1072,UK,North,Keyboard,9,1204,NaN,EXPRESS,Accessories,10836,-776.611518
215,10216,2024-03-26,1183,Canada,West,Tablet,8,639,NaN,EXPRESS,Electronics,5112,-308.500740
216,10217,2023-02-05,1062,Canada,South,Keyboard,6,1329,NaN,EXPRESS,Accessories,7974,1558.888181
251,10252,2022-06-30,1122,Brazil,Central,Smartwatch,3,1226,0.33,Same Day,Electronics,3678,NaN
265,10266,2024-05-03,1141,Australia,South,Smartwatch,6,1235,NaN,EXPRESS,Electronics,7410,1252.189589
267,10268,2022-06-04,1097,UK,South,Mobile,1,297,0.01,Standard,Electronics,297,NaN
281,10282,2022-01-20,1024,Australia,North,Printer,5,103,0.08,standard,Office,515,NaN
297,10298,2023-11-13,1196,France,South,Headphones,7,1736,0.02,EXPRESS,Accessories,12152,NaN
316,10317,2023-10-18,1167,Germany,Central,Mobile,6,650,0.36,Express,Electronics,3900,NaN
318,10319,2023-01-05,1096,France,East,Laptop,9,1546,NaN,standard,Electronics,13914,2730.728786
345,10346,2024-10-05,1157,Canada,South,Smartwatch,8,233,NaN,Standard,Electronics,1864,604.524213
365,10366,2024-11-05,1108,UK,North,Keyboard,7,860,NaN,standard,Accessories,6020,659.850698
377,10378,2024-12-02,1195,Australia,South,Monitor,9,1051,0.39,Standard,Electronics,9459,NaN
400,10401,2023-04-02,1028,Mexico,North,Mouse,4,429,0.29,Same Day,Accessories,1716,NaN
412,10413,2024-05-22,1003,Mexico,Central,Mobile,5,1433,0.04,Standard,Electronics,7165,NaN
415,10416,2023-12-30,1038,Canada,Central,Smartwatch,3,261,NaN,EXPRESS,Electronics,783,76.521334
447,10448,2024-10-29,1014,Japan,Central,Laptop,7,1837,NaN,Express,Electronics,12859,-581.399917
479,10480,2023-05-20,1147,USA,South,Printer,1,107,NaN,Standard,Office,107,39.699011
508,10509,2023-11-29,1044,Germany,West,Mobile,3,1294,0.20,Express,Electronics,3882,NaN
512,10513,2022-02-10,1135,Brazil,South,Mobile,8,159,NaN,Standard,Electronics,1272,79.547088
524,10525,2022-09-13,1085,India,South,Monitor,3,1225,NaN,Express,Electronics,3675,860.788176
545,10546,2023-01-20,1121,Australia,West,Keyboard,7,1301,0.39,Same Day,Accessories,9107,NaN
546,10547,2023-02-09,1142,Mexico,North,laptop,2,658,NaN,Standard,Office,1316,78.489843
569,10570,2022-09-07,1061,Brazil,East,Monitor,4,1736,0.16,Express,Electronics,6944,NaN
639,10640,2022-12-12,1178,France,South,Smartwatch,4,1888,0.32,Express,Electronics,7552,NaN
676,10677,2024-03-16,1061,Brazil,West,Keyboard,7,867,0.20,standard,Accessories,6069,NaN
722,10723,2022-01-04,1164,Brazil,East,Headphones,7,1213,0.23,EXPRESS,Accessories,8491,NaN
723,10724,2023-10-08,1174,Germany,West,Smartwatch,6,1801,0.08,Express,Electronics,10806,NaN
740,10741,2022-05-20,1025,Australia,South,Printer,6,491,NaN,Same Day,Office,2946,397.717361
750,10751,2023-11-21,1011,Mexico,West,Camera,6,1094,0.05,standard,Electronics,6564,NaN
774,10775,2022-03-19,1118,Mexico,North,laptop,7,873,0.07,standard,Electronics,6111,NaN
778,10779,2024-12-01,1007,Germany,Central,Tablet,2,522,NaN,standard,Electronics,1044,-271.528200
800,10801,2024-11-04,1045,Germany,West,Mouse,6,1188,NaN,Same Day,Accessories,7128,1321.138607
815,10816,2024-03-25,1197,Germany,West,Mouse,1,384,0.32,standard,Accessories,384,NaN
823,10824,2022-05-10,1072,Unknown,South,Keyboard,6,565,0.28,standard,Accessories,3390,NaN
870,10871,2024-07-25,1071,Canada,South,Tablet,1,1035,NaN,standard,Electronics,1035,459.135016
890,10891,2024-09-29,1122,India,North,Smartwatch,1,99,NaN,standard,Electronics,99,-21.726702
901,10902,2024-12-22,1035,Japan,North,Headphones,6,651,NaN,Same Day,Accessories,3906,764.206908
916,10917,2024-02-08,1155,Australia,East,Monitor,3,1270,0.17,standard,Electronics,3810,NaN
924,10925,2024-04-10,1001,Mexico,East,Mobile,7,74,NaN,standard,Electronics,518,60.494369
949,10950,2023-04-14,1006,Australia,North,Keyboard,4,61,0.25,Express,Accessories,244,NaN
976,10977,2024-05-03,1090,Mexico,South,Camera,7,1713,NaN,Express,Electronics,11991,-220.324736

In [77]:
df["Profit"].describe()

count     976.000000
mean      547.745905
std      1196.000816
min     -3283.986623
25%       -12.547486
50%       237.711438
75%       872.142206
max      7063.491230
Name: Profit, dtype: float64

In [78]:
#filling profit with median because it contains outlire if we use mean it will affect 
df["Profit"].fillna(df["Profit"].median(), inplace=True)

C:\Users\ACER\AppData\Local\Temp\ipykernel_25224\1751043212.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Profit"].fillna(df["Profit"].median(), inplace=True)

In [79]:
df["Discount"].fillna(0,inplace=True)

C:\Users\ACER\AppData\Local\Temp\ipykernel_25224\1492834683.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Discount"].fillna(0,inplace=True)

In [80]:
df.isnull().sum()

OrderID         0
OrderDate       0
CustomerID      0
Country         0
Region          1
Product         0
Quantity        0
UnitPrice       0
Discount        0
ShippingMode    0
Category        0
Sales           0
Profit          0
dtype: int64

In [81]:
df = df.dropna(subset=["Region"])

In [82]:


df['OrderDate']=pd.to_datetime(df['OrderDate'])

In [83]:
df['Product']=df['Product'].str.title()
df.Product.unique()

array(['Headphones', 'Tablet', 'Smartwatch', 'Keyboard', 'Laptop',
       'Mouse', 'Camera', 'Monitor', 'Mobile', 'Printer'], dtype=object)

In [84]:
df['ShippingMode']=df['ShippingMode'].str.title()
df.Product.unique()

array(['Headphones', 'Tablet', 'Smartwatch', 'Keyboard', 'Laptop',
       'Mouse', 'Camera', 'Monitor', 'Mobile', 'Printer'], dtype=object)

In [85]:
df.Country.unique()

array(['Germany', 'UK', 'Mexico', 'Japan', 'India', 'Unknown', 'Brazil',
       'Canada', 'USA', 'Australia', 'France'], dtype=object)

In [86]:
df.Country = df['Country'].replace({'Unknown': np.nan})

In [87]:
for i in df['Region'].unique():
    a = df[df['Region']==i]['Country']
    df.loc[df['Region']==i,'Country']=df.loc[df['Region']==i,'Country'].fillna(a.mode()[0])

In [88]:
df.to_csv("clean_retail_dataset.csv", index=False)